# Generated by Django 4.0.6 on 2022-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hoconline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.TextField(max_length=50)),
            ],
        ),
    ]
