# Generated by Django 4.0.6 on 2022-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0002_teacher_number_title_alter_hoconline_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='icon')),
            ],
        ),
        migrations.AlterField(
            model_name='teacher_number',
            name='number',
            field=models.IntegerField(),
        ),
    ]
