# Generated by Django 4.0.6 on 2022-07-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0003_intro_alter_teacher_number_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intro',
        ),
    ]
