# Generated by Django 4.0.6 on 2022-07-21 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0005_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='img',
            field=models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
