# Generated by Django 4.0.6 on 2022-07-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0006_alter_intro_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='start_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
