# Generated by Django 4.0.6 on 2022-07-22 02:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0007_start_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='learn_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='img_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_big', models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
                ('img_1', models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
                ('img_2', models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
                ('img_3', models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
                ('img_4', models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
                ('img_5', models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tekylearn.learn_forcing')),
            ],
        ),
    ]
