# Generated by Django 4.0.6 on 2022-07-22 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0008_learn_forcing_img_forcing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_forcing',
            name='img_1',
            field=models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='img_forcing',
            name='img_2',
            field=models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='img_forcing',
            name='img_3',
            field=models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='img_forcing',
            name='img_4',
            field=models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='img_forcing',
            name='img_5',
            field=models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='img_forcing',
            name='img_big',
            field=models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'svg'])]),
        ),
    ]
