# Generated by Django 4.0.6 on 2022-07-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0009_alter_img_forcing_img_1_alter_img_forcing_img_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img_forcing',
        ),
    ]
