# Generated by Django 4.0.6 on 2022-07-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0010_delete_img_forcing'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_big', models.ImageField(upload_to='images/upload')),
                ('img1', models.ImageField(upload_to='images/upload')),
                ('img2', models.ImageField(upload_to='images/upload')),
                ('img3', models.ImageField(upload_to='images/upload')),
                ('img4', models.ImageField(upload_to='images/upload')),
                ('img5', models.ImageField(upload_to='images/upload')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tekylearn.learn_forcing')),
            ],
        ),
    ]
