# Generated by Django 4.0.6 on 2022-07-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0011_img_forcing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img_forcing',
        ),
        migrations.DeleteModel(
            name='learn_forcing',
        ),
    ]
