# Generated by Django 4.0.6 on 2022-07-22 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0012_delete_img_forcing_delete_learn_forcing'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_big', models.ImageField(upload_to='images/upload')),
            ],
        ),
        migrations.CreateModel(
            name='learn_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tekylearn.img_forcing')),
            ],
        ),
    ]
