# Generated by Django 4.0.6 on 2022-07-22 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0013_img_forcing_learn_forcing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn_forcing',
            name='images',
        ),
        migrations.DeleteModel(
            name='img_forcing',
        ),
        migrations.DeleteModel(
            name='learn_forcing',
        ),
    ]
