# Generated by Django 4.0.6 on 2022-07-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0014_remove_learn_forcing_images_delete_img_forcing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='learn_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='img_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_big', models.ImageField(upload_to='images/upload')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tekylearn.learn_forcing')),
            ],
        ),
    ]
