# Generated by Django 4.0.6 on 2022-07-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0015_learn_forcing_img_forcing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_forcing',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='tekylearn.learn_forcing'),
        ),
    ]
