# Generated by Django 4.0.6 on 2022-07-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0016_alter_img_forcing_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title_smail',
            new_name='title_small',
        ),
    ]
