# Generated by Django 4.0.6 on 2022-07-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0019_alter_learn_prize_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn_prize',
            name='img',
            field=models.ImageField(upload_to='tekylearn/static/images/upload'),
        ),
    ]
