# Generated by Django 4.0.6 on 2022-07-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0020_alter_learn_prize_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_forcing',
            name='img_big',
            field=models.ImageField(upload_to='tekylearn/static/images/upload'),
        ),
    ]
