# Generated by Django 4.0.6 on 2022-07-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0021_alter_img_forcing_img_big'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hoconline',
        ),
        migrations.RemoveField(
            model_name='img_forcing',
            name='name',
        ),
        migrations.DeleteModel(
            name='intro',
        ),
        migrations.DeleteModel(
            name='learn_prize',
        ),
        migrations.DeleteModel(
            name='start_learn',
        ),
        migrations.DeleteModel(
            name='teacher_number',
        ),
        migrations.DeleteModel(
            name='title',
        ),
        migrations.DeleteModel(
            name='img_forcing',
        ),
        migrations.DeleteModel(
            name='learn_forcing',
        ),
    ]
