# Generated by Django 4.0.6 on 2022-07-25 14:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tekylearn', '0022_delete_hoconline_remove_img_forcing_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='learn_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('intro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='learn_intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.FileField(upload_to='images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='learn_online',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='learn_parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='tekylearn/static/images/upload')),
            ],
        ),
        migrations.CreateModel(
            name='learn_prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='tekylearn/static/images/upload')),
            ],
        ),
        migrations.CreateModel(
            name='learn_teacher_number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='learn_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title_small', models.CharField(max_length=100)),
                ('title_big', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='start_learn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='img_forcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='tekylearn/staticimages/upload')),
                ('type', models.CharField(max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='tekylearn.learn_forcing')),
            ],
        ),
    ]
