# Generated by Django 4.0.6 on 2022-07-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0023_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_forcing',
            name='type',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
