# Generated by Django 4.0.6 on 2022-07-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0024_alter_img_forcing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='learn_why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='tekylearn/static/images/upload')),
            ],
        ),
    ]
