# Generated by Django 4.0.6 on 2022-07-25 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0025_learn_why'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img_forcing',
            name='img',
            field=models.ImageField(upload_to='tekylearn/static/images/upload'),
        ),
        migrations.AlterField(
            model_name='learn_intro',
            name='img',
            field=models.FileField(upload_to='tekylearn/static/images/upload', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
