# Generated by Django 4.0.6 on 2022-07-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0026_alter_img_forcing_img_alter_learn_intro_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='learn_parent',
        ),
    ]
