# Generated by Django 4.0.6 on 2022-07-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0031_caphoc_registerstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='trungtam',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
