# Generated by Django 4.0.6 on 2022-07-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0032_trungtam_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='caphoc',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_forcing',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_intro',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_online',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_parent',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_prize',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_teacher_number',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_title',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learn_why',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registerstudent',
            name='location',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='start_learn',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
