# Generated by Django 4.0.6 on 2022-07-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0034_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('number', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='tekylearn/static/images/upload')),
            ],
        ),
    ]
