# Generated by Django 4.0.6 on 2022-07-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0035_blog1'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='location',
            field=models.IntegerField(default=0),
        ),
    ]
