# Generated by Django 4.0.6 on 2022-07-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0036_partner_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img_forcing',
            old_name='type',
            new_name='typeimg',
        ),
    ]
