# Generated by Django 4.0.6 on 2022-08-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekylearn', '0037_rename_type_img_forcing_typeimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalRegisterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=30)),
                ('nameparent', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
